language: node_js
dist: trusty
sudo: required
node_js:
- '8'
before_install:
  - export CHROME_BIN=chromium-browser
before_script:
  - export DISPLAY=:99.0
env:
  - GOOGLE_CHROME_BINARY=/usr/bin/google-chrome-beta
