export const LOAD_BOOKMARKS = 'LOAD_BOOKMARKS';
export const LOAD_TAGS = 'LOAD_TAGS';
export const ADD_FILTER = 'ADD_FILTER';
export const REMOVE_FILTER = 'REMOVE_FILTER';
export const BOOKMARKS_FETCH_REQUESTED = 'BOOKMARKS_FETCH_REQUESTED';
export const BOOKMARKS_FETCH_SUCCEEDED = 'BOOKMARKS_FETCH_SUCCEEDED';
